# 1. ä¸ºå·¥ä½œæµå®šä¹‰åå­—
name: ã€ŒGitHub Pagesã€Build & Deploy

# 2. è§¦å‘æ¡ä»¶ä¿®æ”¹ä¸º: å½“ main æˆ– master åˆ†æ”¯, æœ‰ push çš„æ—¶å€™, æ‰§è¡Œä»»åŠ¡
on:
  push:
    branches:
      - master
      - main

# 3. åˆ›å»ºå·¥ä½œæµ
jobs:
  build: # å·¥ä½œæµåç§°
    runs-on: ubuntu-latest # ä¾èµ–ç¯å¢ƒ

    steps: # å·¥ä½œæµæ­¥éª¤
      # step 1. è·å–æºç , æ‹‰å–ä»“åº“ä»£ç 
      - name: Chekcout ğŸ›ï¸ # æ­¥éª¤å
        uses: actions/checkout@master # ä½¿ç”¨æ’ä»¶ => https://github.com/actions/checkout

      # step 2. ä½¿ç”¨æŒ‡å®šç‰ˆæœ¬ node
      - name: Use Node  ğŸ“¦ # æ­¥éª¤å
        uses: actions/setup-node@master # ä½¿ç”¨æ’ä»¶ => https://github.com/actions/setup-node
        with: # æ’ä»¶æºå¸¦å‚æ•°
          node-version: '18' # æŒ‡å®š node ç‰ˆæœ¬

      - name: Update npm
        run: npm install -g npm

      # step 3. å®‰è£…ä¾èµ–å¹¶æ‰“åŒ…
      - name: Install and Build ğŸ”§
        run: |
          npm install turbo@1.10.6 -g
          npm install pnpm -g
          pnpm config set registry https://registry.npmmirror.com
          npm install
          npm run build

      # step 4. é¡¹ç›®éƒ¨ç½², å°†æ‰“åŒ…åçš„äº§ç‰©åˆå¹¶åˆ°æŒ‡å®šçš„åˆ†æ”¯ä¸Š
      - name: Deploy ğŸš€ # æ­¥éª¤å
        uses: JamesIves/github-pages-deploy-action@v4.2.2 # ä½¿ç”¨æ’ä»¶ => https://github.com/JamesIves/github-pages-deploy-action
        with:
          BRANCH: gh-pages # éƒ¨ç½²åˆ†æ”¯
          FOLDER: digtal-dist # æ‰“åŒ…, é™æ€èµ„æºè¾“å‡ºçš„ç›®å½•
