# 1. ä¸ºå·¥ä½œæµå®šä¹‰åå­—
name: ã€ŒGitHub Pagesã€Build & Deploy

# 2. è§¦å‘æ¡ä»¶ä¿®æ”¹ä¸º: å½“ main æˆ– master åˆ†æ”¯, æœ‰ push çš„æ—¶å€™, æ‰§è¡Œä»»åŠ¡
on:
  push:
    branches:
      - master
      - main

# 3. åˆ›å»ºå·¥ä½œæµ
jobs:
  build: # å·¥ä½œæµåç§°
    runs-on: ubuntu-latest # ä¾èµ–ç¯å¢ƒ

    steps: # å·¥ä½œæµæ­¥éª¤
      # step 1. è·å–æºç , æ‹‰å–ä»“åº“ä»£ç 
      - name: Chekcout ğŸ›ï¸ # æ­¥éª¤å
        uses: actions/checkout@master # ä½¿ç”¨æ’ä»¶ => https://github.com/actions/checkout

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies
        shell: bash
        run: pnpm install --no-frozen-lockfile

      # step 3. å®‰è£…ä¾èµ–å¹¶æ‰“åŒ…
      - name: Install and Build ğŸ”§
        run: |
          pnpm config set registry https://registry.npmmirror.com
          pnpm build

      # step 4. é¡¹ç›®éƒ¨ç½², å°†æ‰“åŒ…åçš„äº§ç‰©åˆå¹¶åˆ°æŒ‡å®šçš„åˆ†æ”¯ä¸Š
      - name: Deploy ğŸš€ # æ­¥éª¤å
        uses: JamesIves/github-pages-deploy-action@v4.2.2 # ä½¿ç”¨æ’ä»¶ => https://github.com/JamesIves/github-pages-deploy-action
        with:
          BRANCH: gh-pages # éƒ¨ç½²åˆ†æ”¯
          FOLDER: digital-dist # æ‰“åŒ…, é™æ€èµ„æºè¾“å‡ºçš„ç›®å½•
